### ISSUE TITLE
Notifications when a post moves from DRAFT to PENDING

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-blog#22]
In BLOG it would be good if there was the ability to get notifications when a post goes from DRAFT to PENDING so the editors are aware they have work to do - would the ErFlow plug-in work on blog or is it too customised?

*Added:* 2018-03-14
*Reviewed:*

**Comment by domjngo** [comment]
It should work, I'll investigate and test it on my dev.

**Comment by grange85** [comment]
Erflow installed on Blog
