### ISSUE TITLE
In Blog, images added to galleries are not displaying correctly

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-blog#27]
In Blog, images added to galleries are not displaying correctly unless they are set to 'profile' or 'thumbnail' size.  (see https://blog.nationalarchives.gov.uk/blog/from-tripoli-to-timbuktu/ for example)

If images in galleries are set to profile or thumbnail size, they then display a bit too large and are slightly pixellated (see https://blog.nationalarchives.gov.uk/blog/suffrage-study-day-special-event-schools/ for example)

**Comment by domjngo** [comment]
@grange85 Can we try changing the site URL in settings to HTTPS? And then maybe the wp-config as well. The gallery srcset is generated outside the the_content function, so make_paths_relative function isn't catching it.

**Comment by grange85** [comment]
@domingobishop sadly for multi-site ...

> If, instead, you are changing domains, then the best way to move Multisite is to move the files, edit the .htaccess and wp-config.php (change DOMAIN_CURRENT_SITE and, if the folder name containing Multisite changed, PATH_CURRENT_SITE), and **then manually edit the database. Search for all instances of your domain name, and change them as needed**. This step cannot yet be easily automated. It's safe to search/replace any of the wp_x_posts tables, however do not attempt blanket search/replace without the Search and Replace for WordPress Databases script (aka the interconnectit script). 

https://codex.wordpress.org/Moving_WordPress#Moving_WordPress_Multisite

**Comment by domjngo** [comment]
Ok, no worries. The gallery srcset URLs are dynamically created. I'd need to see how to filter these URLs and do a string replace I guess....
