### ISSUE TITLE
Home page cards not pulling through featured images from blog posts.

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-blog#32]
WordPress leaves the image field blank: you need to put in the URL of the featured image manually.

**Comment by domjngo** [comment]
Yoast isn't returning the og:image. To check Yoast settings.

**Comment by domjngo** [comment]
@grange85 were you able to find out if there was a Yoast setting for this?

**Comment by domjngo** [comment]
There is a work-around for this (manually insert image url)... fixing the issue needs a proper look at SEO meta data managed by Yoast

**Comment by lizbryant** [comment]
Sorry, Andy, this is still not working.

**Comment by grange85** [comment]
Hi @lizbryant - the problem that caused this is fixed - the reason it's not working is now related to the other bug you raised about eventbrite URLs - I've updated that issue to make it clear that it applies to all opengraph calls (EventBrite and blog) - and @netdesignr is taking a look at it.
https://github.com/nationalarchives/tna-child-home/issues/70
